FROM node:8.9.1

WORKDIR /frontend

RUN npm install -g gulp

RUN npm install -g webdriver-manager
RUN webdriver-manager update --standalone --versions.chrome 2.28 --gecko false

RUN npm install -g yarn # FIXME

COPY package.json /frontend
RUN yarn install

COPY . /frontend

CMD gulp
