FROM node:latest

WORKDIR /frontend

ADD yarn.lock  /frontend
ADD package.json  /frontend

ENV NODE_PATH=/frontend/node_modules
ENV PATH=$PATH:/frontend/node_modules/.bin
RUN yarn

WORKDIR /app
ADD . /app
ADD tests/run.sh /app/run.sh

ENTRYPOINT ["/bin/bash", "./run.sh"]
CMD ["test"]
