FROM node:8.9.1

WORKDIR /frontend

RUN npm install -g gulp

RUN npm install -g webdriver-manager
RUN webdriver-manager update --standalone --versions.chrome 2.28 --gecko false

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

COPY package.json /frontend
RUN yarn install

COPY . /frontend

CMD gulp e2e-test
