FROM node:latest

WORKDIR /frontend

COPY yarn.lock  /frontend
COPY package.json  /frontend

ENV PATH=$PATH:/frontend/node_modules/.bin
RUN yarn

WORKDIR /app
COPY . /app
COPY .circleci/dockerfile/run.sh /app/run.sh

ENTRYPOINT ["/bin/bash", "./run.sh"]
CMD ["test"]
