FROM node:8.9.1

WORKDIR /frontend

RUN npm install -g gulp

RUN npm install -g webdriver-manager
RUN webdriver-manager update --standalone --versions.chrome 2.28 --gecko false

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN apt-get install default-jdk

COPY package.json /frontend
RUN yarn install

COPY . /frontend

CMD gulp e2e-test
