FROM node:7.10.1

RUN mkdir -p /frontend

WORKDIR /frontend

RUN npm install -g gulp
RUN npm install -g bower
RUN npm install -g http-server


COPY package.json /frontend
RUN npm install --silent

RUN mkdir -p /frontend/app/bower_components
COPY bower.json /frontend
COPY .bowerrc /frontend
RUN bower install --allow-root

COPY . /frontend
RUN gulp develop-doc

CMD ["http-server", "./app", "-P", "http://localhost:8080/", "-p", "8000"]
