FROM node:current

ADD yarn.lock /yarn.lock
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn

WORKDIR /app
ADD . /app
ADD tests/run.sh /app/run.sh

ENTRYPOINT ["/bin/bash", "./run.sh"]
CMD ["test"]
