# Use the latest image built as this is what is under test
FROM hbpmip/woken:latest

COPY ../web-analytics-starter/woken/config/application.conf /build/src/woken/config/application.conf
COPY ../web-analytics-starter/woken-fed/config/application.conf /build/src/woken-fed/config/application.conf
COPY ../web-analytics-starter/woken-worker1/config/application.conf /build/src/woken-worker1/config/application.conf
COPY ../web-analytics-starter/woken-worker2/config/application.conf /build/src/woken-worker2/config/application.conf

ENV CLUSTER_PORT: 8088 \
    CLUSTER_IP: woken \
    WOKEN_PORT_8088_TCP_ADDR: woken \
    DOCKER_BRIDGE_NETWORK: "webanalyticsstarter_default" \
    LOG_LEVEL: DEBUG \
    KAMON_ENABLED: "yes" \
    ZIPKIN_ENABLED: "yes" \
    PROMETHEUS_ENABLED: "yes" \
    SIGAR_SYSTEM_METRICS: "no" \
    JVM_SYSTEM_METRICS: "yes"
